package com.jds.model.enumClasses;

public enum TypeOfLimitionDoor {
    METAL_THICKNESS,

    WIDTH,
    HEIGHT,
    WIDTH_ACTIVE_LEAF,
    DEPTH,
    LEAF_THICKNESS,

    INTERNAL_OPENING,

    FANLIGHT,
    HEIGHT_FANLIGHT,

    COLOR_DOOR,
    DESIGN_DOOR,
    COLOR_WOOD_PANEL,

    DOORSTEP,
    STAINLESS_STEEL_DOORSTEP,

    FIRST_SEALING_LINE,
    SECOND_SEALING_LINE,
    THIRD_SEALING_LINE,

    TOP_DOOR_TRIM,
    LEFT_DOOR_TRIM,
    RIGHT_DOOR_TRIM,

    TOP_DOOR_TRIM_SIZE,
    LEFT_DOOR_TRIM_SIZE,
    RIGHT_DOOR_TRIM_SIZE,

    STYROFOAM,

    TOP_LOCK,
    LOWER_LOCK,
    HANDLE,
    CLOSER,
    PEEPHOLE,
    PEEPHOLE_POSITION,
    NIGHT_LOCK,
    THRESHOLD,
    END_DOOR_LOCK,
    LOCK_CYLINDER,

    TOP_IN_LOCK_DECOR,
    TOP_OUT_LOCK_DECOR,
    LOWER_IN_LOCK_DECOR,
    LOWER_OUT_LOCK_DECOR,

    TYPE_GLASS,
    TONING,
    ARMOR,

    SHIELD_COLOR,
    SHIELD_DESIGN,
    SHIELD_GLASS,

    SIZE_COST_WIDTH,
    SIZE_COST_HEIGHT
}
