package com.jds.model.modelEnum;

public enum  TypeOfSalaryConst {
    CONSTRUCTOR_COST,
    MARKUP_CONSTRUCTOR,
    CUTTING_COST_PER_SHEET,
    BENDING_COST,
    GUILLOTINE_COST,
    HEIGHT_LIMIT_ONE_LEAF,
    WIDTH_LIMIT_ONE_LEAF,
    HEIGHT_LIMIT_TWO_LEAF,
    WIDTH_LIMIT_TWO_LEAF,
    COST_OVER_LIMIT_ONE_LEAF,
    COST_OVER_LIMIT_TWO_LEAF,
    COST_DOOR_FANLIGHT,
    COST_WELDED_HANDLE,
    COST_WELDING_ADDITIONAL_DOOR_HINGE,
    COST_AMPLIFIER_CLOSER,
    WELDING_FOR_GLASS,
    SQUARES_MODEL_L5,
    COST_THIRD_SEALING_LINE,

    COST_CLEAN_ONE_LEAF,
    COST_CLEAN_TWO_LEAF,
    COST_CLEAN_SMOOTH_PAINT_ONE_LEAF,
    COST_CLEAN_SMOOTH_PAINT_TWO_LEAF,
    COST_CLEAN_SQUARES_L5_PAINT_ONE_LEAF,
    COST_CLEAN_SQUARES_L5_PAINT_TWO_LEAF,
    COST_CLEAN_ADDITIONALLY_HINGE_ONE_LEAF,
    COST_CLEAN_ADDITIONALLY_HINGE_TWO_LEAF,
    COST_CLEAN_THIRD_SEALING_LINE_ONE_LEAF,
    COST_CLEAN_THIRD_SEALING_LINE_TWO_LEAF,
    COST_CLEAN_HOT_ONE_LEAF,
    COST_CLEAN_HOT_TWO_LEAF,

    COST_POLYMER_COLOR_HOT_ONE_LEAF,
    COST_POLYMER_COLOR_HOT_TWO_LEAF,
    COST_POLYMER_COLOR_MDF_ONE_LEAF,
    COST_POLYMER_COLOR_MDF_TWO_LEAF,
    COST_POLYMER_COLOR_ONE_LEAF,
    COST_POLYMER_COLOR_TWO_LEAF,

    COST_ASSEMBLY_HOT_ONE_LEAF,
    COST_ASSEMBLY_HOT_TWO_LEAF,
    COST_ASSEMBLY_MDF_ONE_LEAF,
    COST_ASSEMBLY_MDF_TWO_LEAF,
    COST_ASSEMBLY_ONE_LEAF,
    COST_ASSEMBLY_TWO_LEAF,
    COST_ASSEMBLY_GLASS


}
