package com.jds.model.modelEnum;

public enum TypeOfFurniture {
    TOP_LOCK,
    LOWER_LOCK,
    HANDLE,
    CLOSER,
    PEEPHOLE,
    NIGHT_LOCK,
    THRESHOLD,
    END_DOOR_LOCK,	
	LOCK_CYLINDER,
	ARMOR_GLASS_PELLICLE,
	GLASS_PELLICLE,
	TYPE_GLASS,
	LOCK_DECORATION,
	TT_TURNER,
	DOOR_CLASS,
    TOP_IN_LOCK_DECOR,
    TOP_OUT_LOCK_DECOR,
    LOWER_IN_LOCK_DECOR,
    LOWER_OUT_LOCK_DECOR,
}
