package com.jds.model.modelEnum;

public enum  TypeOfSalaryConst {
    CONSTRUCTOR_COST,
    MARKUP_CONSTRUCTOR,
    CUTTING_COST_PER_SHEET,
    BENDING_COST,
    GUILLOTINE_COST,
    HEIGHT_LIMIT_ONE_LEAF,
    WIDTH_LIMIT_ONE_LEAF,
    HEIGHT_LIMIT_TWO_LEAF,
    WIDTH_LIMIT_TWO_LEAF,
    COST_OVER_LIMIT_ONE_LEAF,
    COST_OVER_LIMIT_TWO_LEAF,
    COST_DOOR_FANLIGHT,
    COST_WELDED_HANDLE,
    COST_WELDING_ADDITIONAL_DOOR_HINGE,
    COST_AMPLIFIER_CLOSER,
    WELDING_FOR_GLASS,
    SQUARES_MODEL_L5,
    COST_THIRD_SEALING_LINE

}
